services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

  app-backend:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./:/home/node/app/

volumes:
  mongo-data: